[package]
name = "tycho-simulation"
version = "0.155.0"
edition = "2021"
description = "Provides tools for interacting with protocol states, calculating spot prices, and quoting token swaps."
repository = "https://github.com/propeller-heads/tycho-simulation"
homepage = "https://www.propellerheads.xyz/tycho"
documentation = "https://docs.propellerheads.xyz/tycho"
keywords = ["propellerheads", "solver", "defi", "dex", "mev"]
license = "MIT"
categories = ["finance", "cryptography::cryptocurrencies"]
readme = "README.md"


[workspace]
members = ["tycho_simulation_py"]

[dependencies]
# Serialization/Deserialization
serde = { version = "1.0", features = ["rc"] }
serde_json = "1.0.105"
uuid = { version = "1.4.1", features = ["serde", "v4", "fast-rng", "macro-diagnostics"] }
hex = "0.4.3"
chrono = { version = "0.4.26", features = ["serde"] }

# Error handling
thiserror = "1"

# Async & concurrency
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.31"

# Logging & Tracing
tracing = "0.1.37"

# Utility
num-traits = "0.2.17"
dotenv = "0.15.0"
itertools = "0.10.5"
enum_delegate = "0.2.0"

# Enum utilities
strum = "0.25.0"
strum_macros = "0.25.2"

# Caching
mini-moka = "0.10"
lazy_static = "1.4.0"

# Tycho dependencies
tycho-common = "0.82.0"
tycho-client = "0.82.0"

# EVM dependencies
foundry-config = { git = "https://github.com/foundry-rs/foundry", rev = "5a552bb0de7126fa35170fd84532bbd3d40cd348", optional = true }
foundry-evm = { git = "https://github.com/foundry-rs/foundry", rev = "5a552bb0de7126fa35170fd84532bbd3d40cd348", optional = true }
solar-config = "=0.1.5"
alloy = { version = "1.0.6", features = ["providers", "signer-local", "rpc-types-eth"], optional = true }
revm = { version = "27.0.3", features = ["alloydb", "serde"], optional = true }
revm-inspectors = { version = "0.26.5", features = ["serde"], optional = true }
num-bigint = { version = "0.4", features = ["serde"] }
tokio-stream = "0.1.16"

# Dialoguer
dialoguer = "0.10.4"

# Ekubo
evm_ekubo_sdk = { version = "0.6.4", features = ["serde"] }

# rfq
reqwest = { version = "0.12.22", optional = true }
async-trait = { version = "0.1.88", optional = true }
tokio-tungstenite = { version = "0.26.2", optional = true }
async-stream = { version = "0.3.6", optional = true }
http = { version = "1.0", optional = true }
prost = { version = "0.13", optional = true }

[dev-dependencies]
tokio-test = "0.4.4"
approx = "0.5.1"
rstest = "0.23.0"
rstest_reuse = "0.7.0"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
  "env-filter",
  "fmt",
] }
tempfile = "3.13.0"

# testing
mockall = "0.13"

# price_printer example
clap = { version = "4.5.3", features = ["derive"] }
anyhow = "1.0.79"
ratatui = "0.29.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
unicode-width = "0.1.13"
tracing-appender = "0.2.3"

# tycho execution for quickstart
tycho-execution = "0.122.0"

[features]
default = ["evm", "rfq"]
network_tests = []
evm = [
  "dep:foundry-config", "dep:foundry-evm", "dep:revm", "dep:revm-inspectors", "dep:alloy",
]
rfq = ["dep:reqwest", "dep:async-trait", "dep:tokio-tungstenite", "dep:async-stream", "dep:http", "dep:prost"]

[profile.bench]
debug = true
